# Find the transpose of a matrix and then multiply it with the original matrix.

In [2]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
transpose = arr.T
print(f"Original Matrix\n: {arr}")
print(f"Transpose Matrix\n: {transpose}")
print(f"Multiply of transpose and original matrix\n: {np.dot(arr, transpose)}")

Original Matrix
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose Matrix
: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Multiply of transpose and original matrix
: [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
