# Multiply two 3×3 matrices.

In [9]:
import numpy as np
arr1 = np.random.randint(1, 10, size = (3, 3))
arr2 = np.random.randint(1, 10, size = (3, 3))
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Result 1 Multiplication of Matrix\n: {arr1 @ arr2}")
print(f"Result 2 Multiplication of Matrix\n: {np.dot(arr1, arr2)}")

Array 1: [[6 7 4]
 [4 7 5]
 [9 6 3]]
Array 2: [[3 7 5]
 [2 4 6]
 [4 5 9]]
Result 1 Multiplication of Matrix
: [[ 48  90 108]
 [ 46  81 107]
 [ 51 102 108]]
Result 2 Multiplication of Matrix
: [[ 48  90 108]
 [ 46  81 107]
 [ 51 102 108]]
