# Create a 2×6 matrix and reshape it into a 3×4 matrix.

In [3]:
import numpy as np
arr = np.arange(1, 13).reshape(2, 6)
reshape_arr = arr.reshape(3, 4)
print(f"Original Matrix is\n {arr}")
print(f"Reshape Matrix is\n {reshape_arr}")

Original Matrix is
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshape Matrix is
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
