# Swap the first and last rows of a matrix and also swap the first and last columns of a matrix.

In [5]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original Matrix\n: {arr}")
arr[[0, -1]] = arr[[-1, 0]]
print(f"After Swaping Rows Matrix\n: {arr}")
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original Matrix\n: {arr}")
arr[:, [0, -1]] = arr[:, [-1, 0]]
print(f"After Swaping Columns Matrix\n: {arr}")

Original Matrix
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Swaping Rows Matrix
: [[7 8 9]
 [4 5 6]
 [1 2 3]]
Original Matrix
: [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Swaping Columns Matrix
: [[3 2 1]
 [6 5 4]
 [9 8 7]]
